<script type="text/javascript">
    require([
        'jquery',
        'mage/url'
    ], function($, url) {

        window.Aplazo = new Function();

        Aplazo.prototype = {
            initialize : function () {
                this.buyWithAplazoId = '#buy_with_aplazo_checkout';
                this.buyWithAplazoSelector = $(this.buyWithAplazoId);

                this.aplazoPaymentAjaxUrl = '<?= $block->escapeHtml($block->getBaseUrl()); ?>aplazopayment/index/transaction';
                this.aplazoErrorClass = '.error-aplazopayment';

                this.initEvents();

            },

            initEvents: function () {
                var that = this;
                $(document).on("click", this.buyWithAplazoId, function() {
                    that.buyWithAplazoEventClick(this);
                });
            },

            buyWithAplazoEventClick: function(_this) {
                return function () {
                    jQuery('body').loader('show');
                    $.ajax({
                        url: _this.aplazoPaymentAjaxUrl,
                        type: 'GET',
                        cache: false,

                        success: function (response) {
                            localStorage.removeItem('mage-cache-storage');
                            jQuery('body').loader('hide');
                            if (response.error === false && response.redirecturl !== null) {
                                let url = response.redirecturl;
                                window.location = url;
                            } else {
                                console.log(response);
                            }
                        },
                        error: function (response) {
                            jQuery('body').loader('hide');
                            console.log(response);
                        }
                    });
                }
            },
        };

        var aplazo = new Aplazo();

        aplazo.initialize();
        window.aplazo = aplazo;

    });

</script>
