<script type="text/javascript">
    require([
        'jquery',
        'mage/url'
    ], function($, url) {

        window.AplazoProduct = new Function();

        AplazoProduct.prototype = {
            initialize : function () {
                this.buyWithAplazoId = '#buy_with_aplazo';
                this.buyWithAplazoSelector = $(this.buyWithAplazoId);

                this.addToCartButtonId = '#product-addtocart-button';
                this.addToCartButtonSelector = $(this.addToCartButtonId);

                this.aplazoPaymentAjaxUrl = '<?= $block->escapeHtml($block->getBaseUrl()); ?>aplazopayment/index/singleTransaction';
                this.aplazoErrorClass = '.error-aplazopayment';

                this.showButton();
                this.initEvents();

            },

            initEvents: function () {
                this.buyWithAplazoSelector.on('click', e => {
                    e.preventDefault();
                    this.addToCartButtonSelector.click();
                });
                this.buyWithAplazoSelector.on('click', this.buyWithAplazoEventClick(this));
            },


            showButton: function() {
                let _this = this;
                let checkAddToCartButton = setInterval(() => {
                    if (_this.addToCartButtonSelector.is(":disabled") === false) {
                        _this.buyWithAplazoSelector.show();
                        clearInterval(checkAddToCartButton);
                    }
                }, 500);
            },

            buyWithAplazoEventClick: function(_this) {
                return function () {
                    let checkAddToCartButton = setInterval(() => {
                        if (_this.addToCartButtonSelector.is(":disabled") === false) {

                            jQuery('body').loader('show');
                            $.ajax({
                                url: _this.aplazoPaymentAjaxUrl,
                                type: 'GET',
                                cache: false,

                                success: function (response) {
                                    localStorage.removeItem('mage-cache-storage');
                                    jQuery('body').loader('hide');
                                    if (response.error === false && response.redirecturl !== null) {
                                        let url = response.redirecturl;
                                        window.location = url;
                                    } else {
                                        console.log(response);
                                    }
                                },
                                error: function (response) {
                                    jQuery('body').loader('hide');
                                    console.log(response);
                                }
                            });
                            clearInterval(checkAddToCartButton);
                        }
                    }, 500);

                }
            },
        };

        var aplazoProduct = new AplazoProduct();

        aplazoProduct.initialize();
        window.aplazo = aplazoProduct;

    });

</script>