<div class="product_lable aplazo_payment">
	<span class="lable"><strong>Aplazo Payment</strong></span>
</div>

<button id="buy_with_aplazo_checkout">Buy with Aplazo</button>
<div class="error-aplazopayment"></div>

<script type="text/javascript">
    require([
        'jquery',
        'mage/url'
    ], function($, url) {

        window.Aplazo = new Function();

        Aplazo.prototype = {
            initialize : function () {
                this.buyWithAplazoId = '#buy_with_aplazo_checkout';
                this.buyWithAplazoSelector = $(this.buyWithAplazoId);

                this.aplazoPaymentAjaxUrl = '<?= $block->getBaseUrl() ?>aplazopayment/ajax/transaction';
                this.aplazoPaymentRedirectUrl = '<?php echo $block->getRedirectUrl() ?>';
                this.aplazoErrorClass = '.error-aplazopayment';
                this.disabledClass = 'disabled';

                this.addingText = 'Processing ...';
                this.buttonText = 'Buy with Aplazo';

                this.initEvents();

            },

            initEvents: function () {
                this.buyWithAplazoSelector.on('click', this.buyWithAplazoEventClick(this));
            },

            buyWithAplazoEventClick: function(_this) {
                return function () {
                    _this.disableButton();
                    $.ajax({
                        url: _this.aplazoPaymentAjaxUrl,
                        type: 'GET',
                        cache: false,

                        success: function (data) {
                            if (data.error === false && data.transactionId !== null) {
                                window.location = _this.aplazoPaymentRedirectUrl + data.transactionId;
                                _this.enableButton();
                            } else {
                                $(_this.aplazoErrorClass).text(data.message).animate({
                                    width: "auto",
                                    color: 'red',
                                    "font-weight": "bold"
                                }, 5000, function() {
                                    $(_this.aplazoErrorClass).text("");
                                });
                                _this.enableButton();
                            }
                        },
                        error: function (data) {
                            console.log(data);
                            _this.enableButton();
                        }
                    });
                }
            },

            disableButton: function () {
                let _this = this;
                _this.buyWithAplazoSelector.text(_this.addingText);
                _this.buyWithAplazoSelector.addClass(_this.disabledClass);
            },

            enableButton: function () {
                let _this = this;
                setTimeout(function () {
                    _this.buyWithAplazoSelector.removeClass(_this.disabledClass);
                    _this.buyWithAplazoSelector.text(_this.buttonText);
                }, 1000);
            }
        };

        var aplazo = new Aplazo();

        aplazo.initialize();
        window.aplazo = aplazo;

    });

</script>
